[supabase]
url = "https://shphlpyzasvylrosamid.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNocGhscHl6YXN2eWxyb3NhbWlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzI2MzAsImV4cCI6MjA2OTc0ODYzMH0.layrRm6BnmiQDwKg6HwGdCh6LaEN31gM7aMETodxrrQ"
